$ErrorActionPreference = "Stop"

$bunCmd = Get-Command bun -ErrorAction SilentlyContinue
if ($bunCmd) {
    $bun = "bun"
} elseif (Test-Path "$env:USERPROFILE\.bun\bin\bun.exe") {
    $bun = "$env:USERPROFILE\.bun\bin\bun.exe"
} else {
    throw "bun not found on PATH or at $env:USERPROFILE\.bun\bin\bun.exe"
}

$sdkPkg = Get-Content "node_modules/@anthropic-ai/claude-agent-sdk/package.json" -Raw | ConvertFrom-Json
$sdkVersion = $sdkPkg.version

# Cross-target downloads can fail on Windows with "Failed to extract executable"
# (oven-sh/bun#25346). Workaround: download the target's official release zip from
# https://github.com/oven-sh/bun/releases/download/bun-v<ver>/<target>.zip and copy
# the extracted `bun` binary to $env:USERPROFILE\.bun\install\cache\<target>-v<ver>
# (darwin-arm64 zip is named bun-darwin-aarch64.zip).
#
# Each target embeds the matching Claude Code native CLI from the SDK's optional
# platform package, so the compiled exe is self-contained and runs outside this
# project directory. Targets whose native package is not installed locally are
# skipped (npm only installs the package for the host platform by default; fetch
# others with e.g. `npm pack @anthropic-ai/claude-agent-sdk-linux-x64` and extract
# into node_modules).
$targets = @(
    @{ target = "bun-windows-x64"; out = "release/cloudcode-win-x64.exe"; native = "claude-agent-sdk-win32-x64";  cli = "claude.exe" },
    @{ target = "bun-darwin-arm64"; out = "release/cloudcode-macos-arm64"; native = "claude-agent-sdk-darwin-arm64"; cli = "claude" },
    @{ target = "bun-darwin-x64";  out = "release/cloudcode-macos-x64";  native = "claude-agent-sdk-darwin-x64";  cli = "claude" },
    @{ target = "bun-linux-x64";   out = "release/cloudcode-linux-x64";  native = "claude-agent-sdk-linux-x64";   cli = "claude" }
)
New-Item -ItemType Directory -Force release | Out-Null
New-Item -ItemType Directory -Force scripts/gen | Out-Null

foreach ($t in $targets) {
    $nativePath = "node_modules/@anthropic-ai/$($t.native)/$($t.cli)"
    if (-not (Test-Path $nativePath)) {
        Write-Warning "Skipping $($t.out): $nativePath not installed (see comment above)."
        continue
    }
    $ext = if ($t.cli -eq "claude.exe") { ".exe" } else { "" }
    $cliFileName = "claude-$sdkVersion-$($t.native -replace 'claude-agent-sdk-','')$ext"
    $entry = "scripts/gen/bin-entry-$($t.target).ts"
    @"
// Generated by scripts/build-binaries.ps1 - do not edit.
import welcomeText from "../../welcome.txt" with { type: "text" };
import claudeCli from "../../$nativePath" with { type: "file" };
import { startFromBinary } from "../bin-runtime.ts";
await startFromBinary(welcomeText, claudeCli, "$cliFileName");
"@ | Out-File -Encoding utf8 $entry
    Write-Host "Building $($t.out) (embeds $nativePath) ..."
    & $bun build --compile --target=$($t.target) $entry --outfile $t.out
    if ($LASTEXITCODE -ne 0) { throw "bun build failed for $($t.target)" }
}
