#!/usr/bin/env bash
set -euo pipefail

if command -v bun >/dev/null 2>&1; then
    bun_cmd="bun"
elif [ -x "$HOME/.bun/bin/bun" ]; then
    bun_cmd="$HOME/.bun/bin/bun"
else
    echo "bun not found on PATH or at $HOME/.bun/bin/bun" >&2
    exit 1
fi

sdk_version=$(node -p "require('./node_modules/@anthropic-ai/claude-agent-sdk/package.json').version")

# Each target embeds the matching Claude Code native CLI from the SDK's optional
# platform package, so the compiled exe is self-contained and runs outside this
# project directory. Targets whose native package is not installed locally are
# skipped (npm only installs the package for the host platform by default; fetch
# others with e.g. `npm pack @anthropic-ai/claude-agent-sdk-linux-x64` and extract
# into node_modules).
targets=(
    "bun-windows-x64:release/cloudcode-win-x64.exe:claude-agent-sdk-win32-x64:claude.exe"
    "bun-darwin-arm64:release/cloudcode-macos-arm64:claude-agent-sdk-darwin-arm64:claude"
    "bun-darwin-x64:release/cloudcode-macos-x64:claude-agent-sdk-darwin-x64:claude"
    "bun-linux-x64:release/cloudcode-linux-x64:claude-agent-sdk-linux-x64:claude"
)

mkdir -p release scripts/gen

for entry in "${targets[@]}"; do
    IFS=: read -r target out native cli <<<"$entry"
    native_path="node_modules/@anthropic-ai/$native/$cli"
    if [ ! -f "$native_path" ]; then
        echo "Skipping $out: $native_path not installed (see comment above)." >&2
        continue
    fi
    ext=""
    [ "$cli" = "claude.exe" ] && ext=".exe"
    cli_file_name="claude-$sdk_version-${native#claude-agent-sdk-}$ext"
    gen="scripts/gen/bin-entry-$target.ts"
    cat > "$gen" <<EOF
// Generated by scripts/build-binaries.sh - do not edit.
import welcomeText from "../../welcome.txt" with { type: "text" };
import claudeCli from "../../$native_path" with { type: "file" };
import { startFromBinary } from "../bin-runtime.ts";
await startFromBinary(welcomeText, claudeCli, "$cli_file_name");
EOF
    echo "Building $out (embeds $native_path) ..."
    "$bun_cmd" build --compile --target="$target" "$gen" --outfile "$out"
done
